excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gautamr.github.io
title: Code finding
email: groy.pi@gmail.com
author: Gautam Roy
description: My awesome new site
paginate: 3
google_analytics: 